INSERT INTO qas.role_qas (name) VALUES ('Директор');
INSERT INTO qas.role_qas (name) VALUES ('Заместитель директора');
INSERT INTO qas.role_qas (name) VALUES ('Начальник отдела');
INSERT INTO qas.role_qas (name) VALUES ('Сотрудник');
INSERT INTO qas.status (name) VALUES ('active');
INSERT INTO qas.status (name) VALUES ('sended');
INSERT INTO qas.status (name) VALUES ('wait');
INSERT INTO qas.status (name) VALUES ('agreed');
INSERT INTO qas.status (name) VALUES ('denied');
INSERT INTO qas.status (name) VALUES ('canceled');
INSERT INTO qas.process_type (name, description, time_to_do) VALUES ('На согласование', 'Заявления от сотрудников', 24);
INSERT INTO qas.process_type (name, description, time_to_do) VALUES ('На ознакомление', 'Приказы, другие документы руководства', 24);
INSERT INTO qas.process_type (name, description, time_to_do) VALUES ('Предложения к разработке', 'Участие сотрудников по производству', 72);